### ISSUE TITLE
Jacoco - Maven Issue

### ISSUE THREAD

**Issue by regbo** [bbottema/generic-object-pool#2]
Hey there, found your projecto in the Stormpot issues. Looks great. However, it looks like whatever version that's currently deployed depends on a jacoco agent to run. The only way I could get it up and going was to either include the agent in every project, or fork your project and remove the build plugin. Here's my fork:

https://github.com/regbo/generic-object-pool-jacoco-removed

The message I am getting is (can't bring up full stack trace at the moment):

````
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_c13123e.Offline+
````
I'm not familiar with jacoco but apparently there is a way to deploy "releases" and when you don't the above error may occur.

**Comment by rahulbhawsar** [comment]
hi @regbo  - 
Jacoco is meant for code coverage report needed only when you are running tests. 
during the release I request you to skip the jacoco `-Djacoco.skip=true` and you will not see the above error in your deployment. 
thanks,

**Comment by bbottema** [comment]
This was addressed long time ago. Jacoco coverage is skipped for released.
